import Head from "next/head";
import Layout from "./../components/Layout";
import { getHomePageData } from "../lib/content";

export default function Home({ data }) {
  return (
    <Layout>
      <Head>
        <title>Jej wnętrza</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>{JSON.stringify(data)}</h1>
      </main>
    </Layout>
  );
}

export async function getStaticProps(context) {
  const data = await getHomePageData();
  return {
    props: { data },
  };
}
