import Head from "next/head";
import Image from "next/image";
import Layout from "./../components/Layout";
import MainSection from "./../components/MainSection";
import { getHomePageData } from "../lib/content";

export default function Home({ data }) {
  return (
    <Layout>
      <Head>
        <title>Jej wnętrza</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="text-blue-dark h-screen grid grid-cols-1 content-start md:grid-cols-main-wide">
        <MainSection id="top" row="1" classes="inline-grid grid-rows-[400px,400px] grid-cols-1 grid-flow-row justify-items-stretch items-stretch">
          <div className="w-full relative row-start-1 col-start-1 z-10" >
            <Image src="/logoDark.svg" layout="fill" alt="logo" />
          </div>
          <div className="w-full relative bg-pink row-start-1 col-start-1 row-span-2">
            <Image src={data.mainPhoto} layout="fill" alt="main" objectFit="cover" />
          </div>
          <div className="row-start-2 col-start-1 z-10 justify-self-end self-baseline pb-10 pr-10">
            <h1>Aranżacje wnętrz</h1>
          </div>
        </MainSection>
        <MainSection id="offer1" row="2">
          <h1 className="text-5xl text-center mb-10">Projektowanie wnętrz</h1>
          <section>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit
          </section>
        </MainSection>
      </main>
    </Layout>
  );
}

export async function getStaticProps(context) {
  const data = await getHomePageData();
  return {
    props: { data },
  };
}
