
import Layout from './../components/Layout';
import Head from 'next/head';

export default function Offer() {
    return (
        <Layout>
      <Head>
        <title>Jej wnętrza - oferta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
          To jest oferta
        </h1>
      </main>
    </Layout>
    )
}
